// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MockConsole2.Data;

#nullable disable

namespace MockConsole2.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20241227175800_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MockLibrary.Models.Bookings", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<int>("BaggageCharge")
                        .HasColumnType("int");

                    b.Property<int>("FlightID")
                        .HasColumnType("int");

                    b.Property<int>("PassengerID")
                        .HasColumnType("int");

                    b.Property<decimal>("TicketCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("MinValue", 5);

                    b.Property<int>("TicketType")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.HasIndex("FlightID");

                    b.HasIndex("PassengerID");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingID = 1,
                            BaggageCharge = 30,
                            FlightID = 2,
                            PassengerID = 1,
                            TicketCost = 51.83m,
                            TicketType = 0
                        },
                        new
                        {
                            BookingID = 2,
                            BaggageCharge = 10,
                            FlightID = 2,
                            PassengerID = 2,
                            TicketCost = 127m,
                            TicketType = 1
                        },
                        new
                        {
                            BookingID = 3,
                            BaggageCharge = 10,
                            FlightID = 3,
                            PassengerID = 3,
                            TicketCost = 140m,
                            TicketType = 1
                        },
                        new
                        {
                            BookingID = 4,
                            BaggageCharge = 15,
                            FlightID = 4,
                            PassengerID = 4,
                            TicketCost = 50m,
                            TicketType = 0
                        },
                        new
                        {
                            BookingID = 5,
                            BaggageCharge = 15,
                            FlightID = 1,
                            PassengerID = 5,
                            TicketCost = 69m,
                            TicketType = 0
                        },
                        new
                        {
                            BookingID = 6,
                            BaggageCharge = 10,
                            FlightID = 5,
                            PassengerID = 6,
                            TicketCost = 127m,
                            TicketType = 1
                        });
                });

            modelBuilder.Entity("MockLibrary.Models.Flights", b =>
                {
                    b.Property<int>("FlightID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightID"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("int");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FlightID");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightID = 1,
                            Country = "Italy",
                            DepartureDate = new DateTime(2025, 1, 12, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Rome",
                            FlightNumber = "IT-001",
                            MaxSeats = 110,
                            Origin = "Dublin"
                        },
                        new
                        {
                            FlightID = 2,
                            Country = "England",
                            DepartureDate = new DateTime(2025, 1, 12, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "London",
                            FlightNumber = "EN-002",
                            MaxSeats = 110,
                            Origin = "Dublin"
                        },
                        new
                        {
                            FlightID = 3,
                            Country = "France",
                            DepartureDate = new DateTime(2025, 1, 12, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Paris",
                            FlightNumber = "FR-001",
                            MaxSeats = 120,
                            Origin = "Dublin"
                        },
                        new
                        {
                            FlightID = 4,
                            Country = "Belgium",
                            DepartureDate = new DateTime(2025, 1, 12, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Brussels",
                            FlightNumber = "BE-001",
                            MaxSeats = 88,
                            Origin = "Dublin"
                        },
                        new
                        {
                            FlightID = 5,
                            Country = "Ireland",
                            DepartureDate = new DateTime(2025, 1, 12, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Dublin",
                            FlightNumber = "DU-001",
                            MaxSeats = 110,
                            Origin = "London"
                        });
                });

            modelBuilder.Entity("MockLibrary.Models.Passengers", b =>
                {
                    b.Property<int>("PassengerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassengerID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("PassengerID");

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            PassengerID = 1,
                            Name = "FredFarnell",
                            PassportNumber = "P010203"
                        },
                        new
                        {
                            PassengerID = 2,
                            Name = "TomMcManus",
                            PassportNumber = "P896745"
                        },
                        new
                        {
                            PassengerID = 3,
                            Name = "BillTrimble",
                            PassportNumber = "P231425"
                        },
                        new
                        {
                            PassengerID = 4,
                            Name = "FredaMcDonald",
                            PassportNumber = "P235678"
                        },
                        new
                        {
                            PassengerID = 5,
                            Name = "MaryMalone",
                            PassportNumber = "P214587"
                        },
                        new
                        {
                            PassengerID = 6,
                            Name = "TomMcManus",
                            PassportNumber = "P893482"
                        });
                });

            modelBuilder.Entity("MockLibrary.Models.Bookings", b =>
                {
                    b.HasOne("MockLibrary.Models.Flights", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MockLibrary.Models.Passengers", "Passenger")
                        .WithMany("Bookings")
                        .HasForeignKey("PassengerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("MockLibrary.Models.Flights", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("MockLibrary.Models.Passengers", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
